
#==================
#=== Input Selects
#==================

input_select:
  irrigation_cycle2_start_time_type:
    options: 
      - Actual Time
      - Sunrise Offset
      - Sunset Offset


#==================
#=== Input Numbers
#==================
input_number:

  #=====================================
  #=== Start time Sunrise/Sunset offset
  #=====================================
  irrigation_cycle2_start_time_sunrise_offset: 
    name: Sunrise Offset
    min: -120
    max: 120
    mode: box
    unit_of_measurement: min
    icon: mdi:weather-sunset-up

  irrigation_cycle2_start_time_sunset_offset: 
    name: Sunset Offset
    min: -120
    max: 120
    mode: box
    unit_of_measurement: min
    icon: mdi:weather-sunset-down


  #=====================================
  #=== Cycle 2 zone durations (Sliders)
  #=====================================
  irrigation_cycle2_zone1_duration: 
    name: Cycle 2 zone2 Duration
    min: 0
    max: 60
    unit_of_measurement: min
    icon: mdi:numeric-1-box-outline

  irrigation_cycle2_zone2_duration: 
    name: Cycle 2 Zone2 Duration
    min: 0
    max: 60
    unit_of_measurement: min
    icon: mdi:numeric-2-box-outline

  irrigation_cycle2_zone3_duration: 
    name: Cycle 2 Zone3 Duration
    min: 0
    max: 60
    unit_of_measurement: min
    icon: mdi:numeric-3-box-outline

  irrigation_cycle2_zone4_duration: 
    name: Cycle 2 Zone4 Duration
    min: 0
    max: 60
    unit_of_measurement: min
    icon: mdi:numeric-4-box-outline

  #=========================================
  #=== Cycle 2 zone durations (Input Boxes)
  #=========================================
  irrigation_cycle2_zone1_duration_box: 
    name: Cycle 2 Zone 1 Duration
    min: 0
    max: 60
    mode: box
    unit_of_measurement: min
    icon: mdi:numeric-1-box-outline

  irrigation_cycle2_zone2_duration_box: 
    name: Cycle 2 Zone 2 Duration
    min: 0
    max: 60
    mode: box
    unit_of_measurement: min
    icon: mdi:numeric-2-box-outline

  irrigation_cycle2_zone3_duration_box: 
    name: Cycle 2 Zone 3 Duration
    min: 0
    max: 60
    mode: box
    unit_of_measurement: min
    icon: mdi:numeric-3-box-outline

  irrigation_cycle2_zone4_duration_box: 
    name: Cycle 2 Zone 4 Duration
    min: 0
    max: 60
    mode: box
    unit_of_measurement: min
    icon: mdi:numeric-4-box-outline


  #=============================================
  #=== Cycle 2 Wait For Entity Timeout Duration
  #=============================================
  irrigation_cycle2_wait_for_entity_name_timeout_duration:
    name: Irrigation Cycle 2 Wait For Entity Timeout Duration
    min: 1
    max: 86400
    mode: box
    unit_of_measurement: sec
    icon: mdi:clock-end


#================
#=== Input Texts
#================
input_text:

  #====================
  #=== Name of Cycle 2
  #====================
  irrigation_cycle2_name:
    name: Cycle 2 Name
    min: 1
    max: 15

  #=================================
  #=== Cycle 2 Wait For Entity Name
  #=================================
  irrigation_cycle2_wait_for_entity_name:
    name: Irrigation Cycle 2 Wait For Entity Name
    min: 1
    max: 50

  #==================================
  #=== Cycle 2 Wait For Entity State
  #==================================
  irrigation_cycle2_wait_for_entity_state:
    name: Irrigation Cycle 2 Wait For Entity State
    min: 1
    max: 50


#====================
#=== Input Datetimes
#====================
input_datetime:

  #=======================
  #=== Cycle 2 start time
  #=======================
  irrigation_cycle2_start_time:
    name: Cycle 2 Start Time
    has_date: false
    has_time: true


#===================
#=== Input Booleans
#===================
input_boolean:

  #=============================
  #=== Cycle 2 Schedule Enabled
  #=============================
  irrigation_cycle2_schedule_enabled:
    name: Cycle 2 Schedule Enabled
    icon: mdi:toggle-switch

  #================================
  #=== Cycle 1 Schedule Today Only
  #================================
  irrigation_cycle2_schedule_today_only:
    name: Cycle 2 Schedule Today Only
    icon: mdi:calendar-today

  #=======================
  #=== Cycle 2 is Running
  #=======================
  irrigation_cycle2_running:
    name: Cycle 2 Running
    icon: mdi:play-circle-outline
    initial: 'off'

  #===============================================
  #=== Cycle 2 durations are adjusted for weather
  #===============================================
  irrigation_cycle2_adjust_for_temperature:
    name: Cycle 2 Adjust For Temperature
    icon: mdi:home-thermometer

  irrigation_cycle2_adjust_for_rainfall:
    name: Cycle 2 Adjust For Rainfall
    icon: mdi:weather-rainy


  #============================
  #=== Cycle 2 wait for entity
  #============================
  irrigation_cycle2_wait_for_entity:
    name: Cycle 2 Wait For Entity
    icon: mdi:timer-lock-open-outline


  #===============================================
  #=== Cycle 2 Wait For Entity Timeout Continue
  #===============================================
  irrigation_cycle2_wait_for_entity_name_timeout_continue:
    name: Irrigation Cycle 2 Wait For Entity Timeout Continue
    icon: mdi:clock-check-outline


#============
#=== Sensors
#============
sensor:
  - platform: template
    sensors:
      #=== Cycle 2 Start Time In Seconds
      irrigation_cycle2_start_time_in_seconds:
        friendly_name: Cycle 2 Start Time In Seconds
        value_template: >
          {{ state_attr('input_datetime.irrigation_cycle2_start_time', 'timestamp') }}
        
      #=== Cycle 2 Duration In Seconds
      irrigation_cycle2_duration_in_seconds:
        friendly_name: Cycle 2 Duration In Seconds
        value_template: >
          {% set durations = expand('group.irrigation_group_cycle2_zone_durations') | map(attribute='state') | map('int') | list | sort(reverse=true) %}
          {% set max = states('input_number.irrigation_number_of_zones') | int %}
          {{ durations[0:max] | sum }}
        attribute_templates:
          zone_duration: >
            {% set ns = namespace(attributes = '{') %}
            {% for zone in states.input_number if zone.object_id.startswith('irrigation_cycle2_zone') and
                                                  zone.object_id.endswith('_duration') %}
              {% if not loop.first %}
                {% set ns.attributes = ns.attributes ~ ',' %}
              {% endif %}

              {% if states('input_number.irrigation_cycle2_zone' ~ loop.index ~ '_duration') | int == 0 %}
                {% set ns.attributes = ns.attributes ~ ' "zone' ~ loop.index ~ '":"0"' %}
              {% else %}
                {% set duration_secs = states('input_number.irrigation_cycle2_zone' ~ loop.index ~ '_duration') | float * 60 %}
                {% set min_duration_secs = states('input_number.irrigation_weather_adjusted_minimum_duration_in_seconds') | float %}
                {% set max_duration_secs = states('input_number.irrigation_weather_adjusted_maximum_duration_in_minutes') | float * 60 %}
                {% set today = ['mon','tue','wed','thu','fri','sat','sun'][now().weekday()] %}

                {# Adjust for rainfall #}
                {% if is_state('input_boolean.irrigation_cycle2_adjust_for_rainfall', 'on') %}
                  {% set duration_secs = duration_secs * states('input_number.irrigation_rainfall_multiplier') | float %}
                {% endif %}

                {# Adjust for temperature #}
                {% if is_state('input_boolean.irrigation_cycle2_adjust_for_temperature', 'on') %}
                  {% set duration_secs = duration_secs * states('input_number.irrigation_temp_multiplier') | float %}
                {% endif %}

                {# Adjust for max/min duration #}
                {% if duration_secs != 0 %}
                  {% if is_state('input_boolean.irrigation_cycle2_adjust_for_rainfall', 'on') or
                        is_state('input_boolean.irrigation_cycle2_adjust_for_temperature', 'on') %}
                    {% if duration_secs > max_duration_secs %}
                      {% set duration_secs = max_duration_secs %}
                    {% elif duration_secs < min_duration_secs %}
                      {% set duration_secs = min_duration_secs %}
                    {% endif %}
                  {% endif %}
                {% endif %}

                {% if is_state('input_boolean.irrigation_cycle2_zone' ~ loop.index ~ '_every_day', 'on') or
                      is_state('input_boolean.irrigation_cycle2_zone' ~ loop.index ~ '_' ~ today, 'on') %}
                  {% if is_state('input_boolean.irrigation_testing_mode', 'on') %}
                    {% set ns.attributes = ns.attributes ~ '"zone' ~ loop.index ~ '": "' ~ (duration_secs / 60) | round() ~ '" ' %}
                  {% else %}
                    {% set ns.attributes = ns.attributes ~ '"zone' ~ loop.index ~ '": "' ~ duration_secs | round()  ~ '" ' %}
                  {% endif %}
                {% else %}
                  {% set ns.attributes = ns.attributes ~ '"zone' ~ loop.index ~ '": "0" ' %}
                {% endif %}
              {% endif %}
            {% endfor %}

            {{ ns.attributes ~ '}'}}


      #=== Actual Zone durations in seconds
      irrigation_cycle2_zone1_actual_duration_in_seconds:
        friendly_name: Cycle 2 Zone 1 Actual Duration In Seconds
        value_template: >
          {% set zone_duration = state_attr('sensor.irrigation_cycle2_duration_in_seconds', 'zone_duration') %}
          {{ zone_duration.zone1 }}

      irrigation_cycle2_zone2_actual_duration_in_seconds:
        friendly_name: Cycle 2 Zone 2 Actual Duration In Seconds
        value_template: >
          {% set zone_duration = state_attr('sensor.irrigation_cycle2_duration_in_seconds', 'zone_duration') %}
          {{ zone_duration.zone2 }}

      irrigation_cycle2_zone3_actual_duration_in_seconds:
        friendly_name: Cycle 2 Zone 3 Actual Duration In Seconds
        value_template: >
          {% set zone_duration = state_attr('sensor.irrigation_cycle2_duration_in_seconds', 'zone_duration') %}
          {{ zone_duration.zone3 }}

      irrigation_cycle2_zone4_actual_duration_in_seconds:
        friendly_name: Cycle 2 Zone 4 Actual Duration In Seconds
        value_template: >
          {% set zone_duration = state_attr('sensor.irrigation_cycle2_duration_in_seconds', 'zone_duration') %}
          {{ zone_duration.zone4 }}
