
#==================
#=== Input Numbers
#==================
input_number:

  #=====================================
  #=== Cycle 3 zone durations (Sliders)
  #=====================================
  irrigation_cycle3_zone1_duration: 
    name: Cycle 3 Zone1 Duration
    min: 0
    max: 60
    unit_of_measurement: min
    icon: mdi:numeric-1-box-outline

  irrigation_cycle3_zone2_duration: 
    name: Cycle 3 Zone2 Duration
    min: 0
    max: 60
    unit_of_measurement: min
    icon: mdi:numeric-2-box-outline

  irrigation_cycle3_zone3_duration: 
    name: Cycle 3 Zone3 Duration
    min: 0
    max: 60
    unit_of_measurement: min
    icon: mdi:numeric-3-box-outline

  irrigation_cycle3_zone4_duration: 
    name: Cycle 3 Zone4 Duration
    min: 0
    max: 60
    unit_of_measurement: min
    icon: mdi:numeric-4-box-outline

  #=========================================
  #=== Cycle 3 zone durations (Input Boxes)
  #=========================================
  irrigation_cycle3_zone1_duration_box: 
    name: Cycle 3 Zone 1 Duration
    min: 0
    max: 60
    mode: box
    unit_of_measurement: min
    icon: mdi:numeric-1-box-outline

  irrigation_cycle3_zone2_duration_box: 
    name: Cycle 3 Zone 2 Duration
    min: 0
    max: 60
    mode: box
    unit_of_measurement: min
    icon: mdi:numeric-2-box-outline

  irrigation_cycle3_zone3_duration_box: 
    name: Cycle 3 Zone 3 Duration
    min: 0
    max: 60
    mode: box
    unit_of_measurement: min
    icon: mdi:numeric-3-box-outline

  irrigation_cycle3_zone4_duration_box: 
    name: Cycle 3 Zone 4 Duration
    min: 0
    max: 60
    mode: box
    unit_of_measurement: min
    icon: mdi:numeric-4-box-outline


#================
#=== Input Texts
#================
input_text:

  #====================
  #=== Name of Cycle 3
  #====================
  irrigation_cycle3_name:
    name: Cycle 3 Name
    min: 1
    max: 15


#===================
#=== Input Booleans
#===================
input_boolean:

  #=======================
  #=== Cycle 3 is Running
  #=======================
  irrigation_cycle3_running:
    name: Cycle 3 Running
    icon: mdi:play-circle-outline
    initial: 'off'


#============
#=== Sensors
#============
sensor:
  - platform: template
    sensors:
      #=== Cycle 3 Duration In Seconds
      irrigation_cycle3_duration_in_seconds:
        friendly_name: Cycle 3 Duration In Seconds
        value_template: >
          {% set durations = expand('group.irrigation_group_cycle3_zone_durations') | map(attribute='state') | map('int') | list | sort(reverse=true) %}
          {% set max = states('input_number.irrigation_number_of_zones') | int %}
          {{ durations[0:max] | sum }}
        attribute_templates:
          zone_duration: >
            {% set ns = namespace(attributes = '{') %}
            {% for zone in states.input_number if zone.object_id.startswith('irrigation_cycle3_zone') and
                                                  zone.object_id.endswith('_duration') %}
              {% if not loop.first %}
                {% set ns.attributes = ns.attributes ~ ',' %}
              {% endif %}

              {% set duration_secs = states('input_number.irrigation_cycle3_zone' ~ loop.index ~ '_duration') | float * 60 %}
              {% if is_state('input_boolean.irrigation_testing_mode', 'on') %}
                {% set ns.attributes = ns.attributes ~ '"zone' ~ loop.index ~ '": "' ~ (duration_secs / 60) | round() ~ '" ' %}
              {% else %}
                {% set ns.attributes = ns.attributes ~ '"zone' ~ loop.index ~ '": "' ~ duration_secs | round()  ~ '" ' %}
              {% endif %}
            {% endfor %}

            {{ ns.attributes ~ '}'}}


      #=== Actual Zone durations in seconds
      irrigation_cycle3_zone1_actual_duration_in_seconds:
        friendly_name: Cycle 3 Zone 1 Actual Duration In Seconds
        value_template: >
          {% set zone_duration = state_attr('sensor.irrigation_cycle3_duration_in_seconds', 'zone_duration') %}
          {{ zone_duration.zone1 }}

      irrigation_cycle3_zone2_actual_duration_in_seconds:
        friendly_name: Cycle 3 Zone 2 Actual Duration In Seconds
        value_template: >
          {% set zone_duration = state_attr('sensor.irrigation_cycle3_duration_in_seconds', 'zone_duration') %}
          {{ zone_duration.zone2 }}

      irrigation_cycle3_zone3_actual_duration_in_seconds:
        friendly_name: Cycle 3 Zone 3 Actual Duration In Seconds
        value_template: >
          {% set zone_duration = state_attr('sensor.irrigation_cycle3_duration_in_seconds', 'zone_duration') %}
          {{ zone_duration.zone3 }}

      irrigation_cycle3_zone4_actual_duration_in_seconds:
        friendly_name: Cycle 3 Zone 4 Actual Duration In Seconds
        value_template: >
          {% set zone_duration = state_attr('sensor.irrigation_cycle3_duration_in_seconds', 'zone_duration') %}
          {{ zone_duration.zone4 }}
